codecov:
  branch: master
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: 70...100
  status:
    changes: false
    patch: false
    project:
      default:
        target: 90%
comment: false
