# Services used for integration tests
version: '3'
services:
  etcd-test:
    image: quay.io/coreos/etcd
    ports:
      - $ETCD_TEST_LISTEN_PORT:2379
      - $ETCD_TEST_PEER_PORT:2380
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
  vault-test:
    image: vault
    ports:
      - $VAULT_TEST_PORT:8200
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: $VAULT_TEST_ROOT_TOKEN
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    entrypoint: vault server -dev
