version: 2
jobs:
  build:
    docker:
      - image: golang:1.9
      - image: quay.io/coreos/etcd:v3.2.5
      - image: vault:0.8.1
        environment:
          VAULT_DEV_ROOT_TOKEN_ID: test
          VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
          SKIP_SETCAP: "true"
        entrypoint: vault server -dev
    working_directory: /go/src/github.com/fragments/fragments
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dep-{{ checksum "Gopkg.lock" }}

      - run:
          name: Install dependencies
          command: |
            go get github.com/golang/dep/cmd/dep
            dep ensure -v

      - save_cache:
          key: v1-dep-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
            - /go/pkg/dep

      - run:
          name: Install gometalinter
          command: |
            go get -u github.com/alecthomas/gometalinter
            gometalinter --install --force

      - run:
          name: Run gometalinter
          environment:
            CGO_ENABLED: 0
          command: |
            gometalinter \
              --vendor \
              --vendored-linters \
              --skip internal/filestore/mocks \
              --skip internal/backend/mocks \
              --sort=severity \
              --aggregate \
              --disable-all \
              --enable=errcheck \
              --enable=gas \
              --enable=goconst \
              --enable=golint \
              --enable=ineffassign \
              --enable=interfacer \
              --enable=megacheck \
              --enable=misspell \
              --enable=structcheck \
              --enable=unconvert \
              --enable=varcheck \
              --enable=vet \
              --enable=vetshadow \
              --deadline=300s \
              --concurrency=4 \
              ./...

      - run:
          name: Install netcat
          command: |
            apt-get update && apt-get -y install netcat && apt-get clean

      - run:
          name: Wait for ETCD
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 2379 && echo Ok && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for ETCD && exit 1

      - run:
          name: Wait for Vault
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 8200 && echo Ok && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Vault && exit 1

      - run:
          name: Test
          environment:
            ETCD_TEST_LISTEN_PORT: 2379
            ETCD_TEST_PEER_PORT: 2380
            VAULT_TEST_PORT: 8200
            VAULT_TEST_ROOT_TOKEN: test
          command: |
            bash scripts/test.sh
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      - run:
          name: Configure build
          command: |
            export CGO_ENABLED=0
            mkdir -p /out

      - run:
          name: Build
          command: |
            go build -ldflags="-s -w" -o /out/fragments ./cmd/fragments
