// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"encoding/json"

	"github.com/pkg/errors"
)

// MarshalDeployment marshals t to a json encoded byte array.
func MarshalDeployment(t *Deployment) ([]byte, error) {
	if t == nil {
		return nil, errors.New("deployment is nil")
	}
	s, err := json.Marshal(t)
	if err != nil {
		return nil, errors.Wrap(err, "could not marshal deployment")
	}
	return s, nil
}

// UnmarshalDeployment unmarshals a json encoded *Deployment to t
func UnmarshalDeployment(s []byte, t *Deployment) error {
	if t == nil {
		return errors.New("target deployment is nil")
	}
	if err := json.Unmarshal(s, t); err != nil {
		return errors.Wrap(err, "could not unmarshal deployment")
	}
	return nil
}
