// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"io/ioutil"
	"testing"

	"github.com/fragments/fragments/pkg/testutils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarshalDeployment(t *testing.T) {
	// Marshal
	_, err := MarshalDeployment(nil)
	require.Error(t, err)
	s, err := MarshalDeployment(mockDeployment)
	require.NoError(t, err)
	testutils.AssertGolden(t, string(s), "testdata/GoldenDeployment.json")

	// Unmarshal
	var m Deployment
	s, err = ioutil.ReadFile("testdata/GoldenDeployment.json")
	require.NoError(t, err)
	err = UnmarshalDeployment(nil, nil)
	require.Error(t, err)
	err = UnmarshalDeployment(s, nil)
	require.Error(t, err)
	err = UnmarshalDeployment(nil, &m)
	require.Error(t, err)
	err = UnmarshalDeployment(s, &m)
	require.NoError(t, err)
	assert.EqualValues(t, *mockDeployment, m)
}
