// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"encoding/json"

	"github.com/pkg/errors"
)

// MarshalEnvironment marshals t to a json encoded byte array.
func MarshalEnvironment(t *Environment) ([]byte, error) {
	if t == nil {
		return nil, errors.New("environment is nil")
	}
	s, err := json.Marshal(t)
	if err != nil {
		return nil, errors.Wrap(err, "could not marshal environment")
	}
	return s, nil
}

// UnmarshalEnvironment unmarshals a json encoded *Environment to t
func UnmarshalEnvironment(s []byte, t *Environment) error {
	if t == nil {
		return errors.New("target environment is nil")
	}
	if err := json.Unmarshal(s, t); err != nil {
		return errors.Wrap(err, "could not unmarshal environment")
	}
	return nil
}
