// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"io/ioutil"
	"testing"

	"github.com/fragments/fragments/pkg/testutils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarshalEnvironment(t *testing.T) {
	// Marshal
	_, err := MarshalEnvironment(nil)
	require.Error(t, err)
	s, err := MarshalEnvironment(mockEnvironment)
	require.NoError(t, err)
	testutils.AssertGolden(t, string(s), "testdata/GoldenEnvironment.json")

	// Unmarshal
	var m Environment
	s, err = ioutil.ReadFile("testdata/GoldenEnvironment.json")
	require.NoError(t, err)
	err = UnmarshalEnvironment(nil, nil)
	require.Error(t, err)
	err = UnmarshalEnvironment(s, nil)
	require.Error(t, err)
	err = UnmarshalEnvironment(nil, &m)
	require.Error(t, err)
	err = UnmarshalEnvironment(s, &m)
	require.NoError(t, err)
	assert.EqualValues(t, *mockEnvironment, m)
}
