// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"io/ioutil"
	"testing"

	"github.com/fragments/fragments/pkg/testutils"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarshalFunction(t *testing.T) {
	// Marshal
	_, err := MarshalFunction(nil)
	require.Error(t, err)
	s, err := MarshalFunction(mockFunction)
	require.NoError(t, err)
	testutils.AssertGolden(t, string(s), "testdata/GoldenFunction.json")

	// Unmarshal
	var m Function
	s, err = ioutil.ReadFile("testdata/GoldenFunction.json")
	require.NoError(t, err)
	err = UnmarshalFunction(nil, nil)
	require.Error(t, err)
	err = UnmarshalFunction(s, nil)
	require.Error(t, err)
	err = UnmarshalFunction(nil, &m)
	require.Error(t, err)
	err = UnmarshalFunction(s, &m)
	require.NoError(t, err)
	assert.EqualValues(t, *mockFunction, m)
}
