// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"encoding/json"

	"github.com/pkg/errors"
)

// MarshalFunction marshals t to a json encoded byte array.
func MarshalFunction(t *Function) ([]byte, error) {
	if t == nil {
		return nil, errors.New("function is nil")
	}
	s, err := json.Marshal(t)
	if err != nil {
		return nil, errors.Wrap(err, "could not marshal function")
	}
	return s, nil
}

// UnmarshalFunction unmarshals a json encoded *Function to t
func UnmarshalFunction(s []byte, t *Function) error {
	if t == nil {
		return errors.New("target function is nil")
	}
	if err := json.Unmarshal(s, t); err != nil {
		return errors.Wrap(err, "could not unmarshal function")
	}
	return nil
}
