// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package model

import (
	"encoding/json"

	"github.com/pkg/errors"
)

// MarshalPendingUpload marshals t to a json encoded byte array.
func MarshalPendingUpload(t *PendingUpload) ([]byte, error) {
	if t == nil {
		return nil, errors.New("pending-upload is nil")
	}
	s, err := json.Marshal(t)
	if err != nil {
		return nil, errors.Wrap(err, "could not marshal pending-upload")
	}
	return s, nil
}

// UnmarshalPendingUpload unmarshals a json encoded *PendingUpload to t
func UnmarshalPendingUpload(s []byte, t *PendingUpload) error {
	if t == nil {
		return errors.New("target pending-upload is nil")
	}
	if err := json.Unmarshal(s, t); err != nil {
		return errors.Wrap(err, "could not unmarshal pending-upload")
	}
	return nil
}
